### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by sadioci2**
added the new environnment variable_Update Dockerfile

### CODE REVIEW

**Review by s7rosine — COMMENTED** [review]
looks good for me the env you added

**Review by sandargo — APPROVED** [review]

**Review by sandargo — COMMENTED** [review]
we are good to go, i think. Great!

**Comment by sadioci2** [comment]
@s7rosine ; @sandargo can you please re-review again?

**Review by s7rosine — COMMENTED** [review]
approuve

**Review by THIMONE-NOUPA — APPROVED** [review]

**Comment by EDEMOS80** [comment]
this is ok to go

**Pull request merged**
